version: '3.9'

services:
  discordbot:
    container_name: discordbot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DEBIAN_FRONTEND=noninteractive
