version: '3.9'
services:
  backend:
    build: .
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql/mysql-server:8.0.27
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: discordbot
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - "33066:3306"
