name: Docker Image CI

on:
  push:
    branches: [ master, master/* ]
  pull_request:
    branches: [ master, master/* ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
      touch .env
      docker build . --file Dockerfile --tag my-image-name:$(date +%s)
