name: Docker Compose CI
on:
  push:
    branches:
      - master
      - master/*
  pull_request:
    branches:
      - master
      - master/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker images
        run: |
          sudo touch .env
          docker compose build
